config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  resources :uploads, only: [:new, :create]
end

app/models/Upload.rb
class Upload < ApplicationRecord
    # Configurações para o Active Storage, se necessário
    has_one_attached :file
  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/dado.rb
class Dado < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:google_oauth2]
    def self.from_omniauth(auth)
        where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
            user.email = auth.info.email
            user.password = Devise.friendly_token[0,20]
            user.avatar_url = auth.info.image 
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  def new
    @receita_total = flash[:receita_total]
  end

  def create
    if params[:upload].present? && params[:upload][:file].present?
      file = params[:upload][:file].tempfile
      receita_total = normalize_and_save_data(file)
      flash[:receita_total] = receita_total

      redirect_to new_upload_path, notice: "Arquivo enviado e normalizado."
    else
      flash.now[:alert] = "Selecione um arquivo para enviar"
      render :new
    end
  end

  private

  def normalize_and_save_data(file)
    receita_total = 0

    File.foreach(file, encoding: "UTF-8") do |line|
      fields = line.chomp.split("\t")
      data = {
        purchaser_name: fields[0],
        item_description: fields[1],
        item_price: fields[2].to_f,
        purchase_count: fields[3].to_i,
        merchant_address: fields[4],
        merchant_name: fields[5]
      }

      Dado.create(data)

      receita_total += data[:item_price] * data[:purchase_count]
    end
    receita_total
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

def google_oauth2
    user = User.from_omniauth(auth)
    if user.present?
        sign_out_all_scopes
        flash[:success] = t 'devise.omniout_callbacks.success', kind: 'Google'
        sign_in_and_redirect user, event: :authentication
       
    else
        flash[:alert] = 
        t 'devise.omniauth_callbacks.failture', kind: 'Google', reason: '#{auth.info.email} is not authorized.'
        redirect_to new_user_session_path 
    end

end



  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
  def auth
    @auth ||= request.env['omniauth.auth']
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  def after_sign_out_path_for(_resource_or_scope)
    new_user_session_path
  end
  def after_sign_in_path_for(resource_or_scope)
    stored_location_for(resource_or_scope)||root_path
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/upload_helper.rb
module UploadHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Desafio</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.2/dist/css/bootstrap.min.css" rel="stylesheet">
  <style>
    /* Estilo personalizado */
    body {
      background-color: #f0f0f0;
      padding: 20px;
    }
    .container {
      max-width: 600px;
      background-color: #fff;
      padding: 20px;
      border: 1px solid #ddd;
      border-radius: 5px;
      margin: 0 auto;
    }
    .btn-gmail {
      background-color: #4285F4;
      color: #fff;
    }
    .btn-gmail:hover {
      background-color: #357AE8;
    }
    .btn-gmail:focus {
      box-shadow: none;
    }
    .form-group label {
      font-weight: bold;
    }
    .revenue {
      background-color: #D7F3E3;
      border: 1px solid #9DE0B5;
      padding: 10px;
      border-radius: 5px;
      margin-top: 20px;
      text-align: center;
    }
  </style>
  <body>
    <%= yield %>
  </body>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.2/dist/js/bootstrap.min.js"></script>
</html>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bem-vindo</title>
</head>
<body>
  <div class="container">
    <h1 class="text-center">Seja bem-vindo</h1>
    <% if current_user %>
      <h2><%= current_user.email %></h2>
      <%= link_to "Faça upload de um arquivo", new_upload_path, class: "btn btn-gmail btn-block" %>
      <%= link_to "Editar Conta", edit_user_registration_path, class: "btn btn-secondary btn-block" %>
      <%= button_to "Logout", destroy_user_session_path, class: "btn btn-secondary btn-block", data: { turbo: "false" }, method: :delete %>
    <% else %>
      <%= link_to "Login", new_user_session_path, class: "btn btn-gmail btn-block" %>
      <%= link_to "Criar Conta", new_user_registration_path, class: "btn btn-secondary btn-block" %>
    <% end %>
  </div>

</body>
</html>

app/views/uploads/new.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Upload de Arquivo</title>

</head>
<body>
  <div class="container">
    <h1 class="text-center">Upload de Arquivo</h1>
    <form action="<%= uploads_path %>" method="post" enctype="multipart/form-data">
      <div class="form-group">
        <label for="file">Selecione um arquivo:</label>
        <input type="file" id="file" name="upload[file]" class="form-control-file">
      </div>
      <div class="form-group text-center">
        <input type="submit" value="Enviar" class="btn btn-gmail">
      </div>
    </form>
    <% if flash[:receita_total] %>
      <div class="revenue">
        <h2>Receita Total: <%= number_to_currency(flash[:receita_total], unit: "R$", precision: 2) %></h2>
      </div>
    <% end %>
  </div>
 
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.2/dist/js/bootstrap.min.js"></script>
</body>
</html>